name: CI
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nasm
        run: sudo apt-get install nasm
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python3 run_tests.py
      - name: Run mypy
        run: mypy --strict src/main.py
    timeout-minutes: 2
